#%RAML 1.0
title: testforjenkins

/test:
  get:
    responses:
      200:
        body:
          application/json:
            example:
              {
              "message":"Hello Nikki_Reddie"
              }
/run:
  get:
    responses:
      200:
        body:
          application/json:
            example:
              {
              "message":"BYEEEEEE  Nikki"
              }
              
